### ISSUE TITLE
error-p option in make-instance

### ISSUE THREAD

**Issue by Rudolph-Miller** [mmontone/clavier#1]
I want to use validator like this
```Lisp
(let ((validator (make-instance 'boolean-validator :error-p t)))
    (funcall validator "hi"))
=> #<VALIDATION-ERROR hi: hi is not a boolean {1003B01EF3}>
```

What do you say to this option?

**Comment by mmontone** [comment]
Ok. But why you do you prefer it to the current
```lisp
(let ((validator (make-instance 'boolean-validator)))
    (funcall validator "hi" :error-p t))
```
??

To me it makes more sense to decide if you want errors or not at the moment of the validation, not the validator creation.

**Comment by Rudolph-Miller** [comment]
When I use this library, I just create a `validator` with `make-instnce`, and I use this sometimes in some place. I feel `(funcall validator value :error-p t)` each time is redundant, then I
```Lisp
(defun my-validator (value)
  (funcall validator value :error-p t))
```
. It can solve the problem actually, though, I feel it's useful and simple solution to pass `:error-p t` to `make-instance`.

**Comment by mmontone** [comment]
On 10/02/15 10:47, Rudolph Miller wrote:
>
> When I use this library, I just create a |validator| with
> |make-instnce|, and I use this sometimes in some place. I feel
> |(funcall validator value :error-p t)| each time is redundant, then I
>
> (defun my-validator (value)
>   (funcall validator value :error-p t))
>
> . It can solve the problem actually, though, I feel it's useful and
> simple solution to pass |:error-p t| to |make-instance|.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mmontone/clavier/issues/1#issuecomment-73701111>.
>
Ok. But note that :error-p is bound to a dynamic variable
*signal-validation-errors*.


So, (setf *signal-validation-errors* t) somewhere before the validations
solves your problem.


What do you think of that? Still prefer the :error-p in make-instance?

**Comment by Rudolph-Miller** [comment]
I see. `*signal-validation-errors*` is the default value of `:error-p`.
It's good enough for my usage.
thx :smile:
