### ISSUE TITLE
LEN validator: no message, min-message and max-message are not displayed

### ISSUE THREAD

**Issue by vindarel** [mmontone/clavier#5]
Hello,

it seems that `:min-message` and `:max-message` are not displayed. Also why not have a `:message`?

```lisp
(defun len (&key min max message min-message max-message)
  (make-instance 'length-validator
		 :min min
		 :max max
                 :message message  <---- adding message but this creates an error on validation.
		 :min-message min-message
		 :max-message max-message))
```

(will send PR later if I confirm the needs)

**Comment by vindarel** [comment]
see https://github.com/mmontone/clavier/pull/8

but it doesn't seem enough, if no :message I get

> The function COMMON-LISP:NIL is undefined.

in validate.

**Comment by mmontone** [comment]
I've observed the same. And I'm making a patch.

**Comment by mmontone** [comment]
The implementation of validation messages is not great. I'm thinking of a way to improve.

**Comment by mmontone** [comment]
I've pushed some commits. Is this better?

I'm not happy with validation messages yet. Like, should the object being validated appear on the validation error message or not (could be configurable). But that's part of another issue.
