### ISSUE TITLE
How would you allow a blank field and validate if non blank?

### ISSUE THREAD

**Issue by vindarel** [mmontone/clavier#7]
Say we have a form field that can be empty, but when non empty it should be validated. Can we express that?

I tried with a `||` and `non-blank` or `blank` but it isn't the right logic.

Is this expected to be done on this layer?

---

I can add this meaning on my side, but this looks like it should be done inside the validation library.

```lisp
(defun my-validators ()
  (dict 'isbn (list :allow-blank
                    (clavier:not-blank)
                    (clavier:len :min 10 :max 13))
  …))

…

      (loop for validator in (validators)
            if (and (eql :allow-blank validator)
                    (str:blankp val))
              return t
            else
              do (unless (keywordp validator)
                   (multiple-value-bind (success msg)
                       (clavier:validate validator val)
                     …
```

Best,

---

I tried to create a new validator class, but this won't compile: 

> Cannot CHANGE-CLASS objects into CLASS metaobjects.

```lisp

(defclass allow-blank-validator (validator)
  ()
  (:metaclass closer-mop:funcallable-standard-class))
```

**Comment by mmontone** [comment]
I see some trickiness and in the implementation, and this is an old lib, and an old self :)

**Comment by mmontone** [comment]
The implementation of custom validators works for me:

```lisp
CL-USER> (defclass allow-blank-validator (clavier:validator)
  ()
  (:metaclass closer-mop:funcallable-standard-class))

#<SB-MOP:FUNCALLABLE-STANDARD-CLASS COMMON-LISP-USER::ALLOW-BLANK-VALIDATOR>
```

So you have something wrong.

**Comment by vindarel** [comment]
I understand^^

There could be a place for this feature. I see one method that validates a list of validators:

```lisp

(defmethod %validate ((validator validator-collection) object &rest args)
  (loop for validator in (validators validator)
       do (validate validator object :error-p t)))

;; test:

;; validator collection
(deftest validator-collection-test ()
  (let ((validator (make-instance 'validator-collection :validators
				(list (not-blank "Fullname is required")
				      (fn (lambda (x)
					    (> (length x) 2))
					  "Fullname is too short")))))
    (let ((person (make-instance 'person)))
      (signals validation-error
	(funcall validator (fullname person))))
    
    (let ((person (make-instance 'person :fullname "M")))
      (signals validation-error
	(funcall validator (fullname person))))
    
    (let ((person (make-instance 'person :fullname "Mariano")))
      (finishes (funcall validator (fullname person))))))
```

(but why a collection object and not a simple list?)

maybe the feature can be inserted here in this loop.

**Comment by mmontone** [comment]
> Say we have a form field that can be empty, but when non empty it should be validated. Can we express that?
> 
> I tried with a `||` and `non-blank` or `blank` but it isn't the right logic.

Why is it not?

Like this : ?

```lisp
(defparameter *validator* (clavier:|| (clavier:blank) (clavier:&& (clavier:is-a-string) (clavier:len :min 10))))

(funcall *validator* "asdfasdfasdf") =>
T
NIL

(funcall *validator* "asdf")
NIL
"Should be blank and \"asdf\" is not a string or Length of \"asdf\" is less than 10"

(funcall *validator* 2) =>
NIL
"2 is not a string"
```

(you need latest commit to test this properly)

**Comment by vindarel** [comment]
yes it works :) Thank you very much :rocket:  

Ideally it could be made easier. I'm trying a bit…

**Comment by vindarel** [comment]
I like my idea of using a keyword. It would be shorter.
